/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as LayoutImport } from "./routes/_layout";

// Create Virtual Routes

const TableLazyImport = createFileRoute("/table")();
const PostsLazyImport = createFileRoute("/posts")();
const ContactLazyImport = createFileRoute("/contact")();
const AboutLazyImport = createFileRoute("/about")();
const LayoutIndexLazyImport = createFileRoute("/_layout/")();
const PostPostIdLazyImport = createFileRoute("/post/$postId")();
const authLoginLazyImport = createFileRoute("/(auth)/login")();

// Create/Update Routes

const TableLazyRoute = TableLazyImport.update({
  path: "/table",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/table.lazy").then((d) => d.Route));

const PostsLazyRoute = PostsLazyImport.update({
  path: "/posts",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/posts.lazy").then((d) => d.Route));

const ContactLazyRoute = ContactLazyImport.update({
  path: "/contact",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/contact.lazy").then((d) => d.Route));

const AboutLazyRoute = AboutLazyImport.update({
  path: "/about",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/about.lazy").then((d) => d.Route));

const LayoutRoute = LayoutImport.update({
  id: "/_layout",
  getParentRoute: () => rootRoute,
} as any);

const LayoutIndexLazyRoute = LayoutIndexLazyImport.update({
  path: "/",
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import("./routes/_layout.index.lazy").then((d) => d.Route),
);

const PostPostIdLazyRoute = PostPostIdLazyImport.update({
  path: "/post/$postId",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/post.$postId.lazy").then((d) => d.Route));

const authLoginLazyRoute = authLoginLazyImport
  .update({
    path: "/login",
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import("./routes/(auth)/login.lazy").then((d) => d.Route));

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_layout": {
      id: "/_layout";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof LayoutImport;
      parentRoute: typeof rootRoute;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/contact": {
      id: "/contact";
      path: "/contact";
      fullPath: "/contact";
      preLoaderRoute: typeof ContactLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/posts": {
      id: "/posts";
      path: "/posts";
      fullPath: "/posts";
      preLoaderRoute: typeof PostsLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/table": {
      id: "/table";
      path: "/table";
      fullPath: "/table";
      preLoaderRoute: typeof TableLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/(auth)/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof authLoginLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/post/$postId": {
      id: "/post/$postId";
      path: "/post/$postId";
      fullPath: "/post/$postId";
      preLoaderRoute: typeof PostPostIdLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/_layout/": {
      id: "/_layout/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof LayoutIndexLazyImport;
      parentRoute: typeof LayoutImport;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({ LayoutIndexLazyRoute }),
  AboutLazyRoute,
  ContactLazyRoute,
  PostsLazyRoute,
  TableLazyRoute,
  authLoginLazyRoute,
  PostPostIdLazyRoute,
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/about",
        "/contact",
        "/posts",
        "/table",
        "/login",
        "/post/$postId"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/"
      ]
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/contact": {
      "filePath": "contact.lazy.tsx"
    },
    "/posts": {
      "filePath": "posts.lazy.tsx"
    },
    "/table": {
      "filePath": "table.lazy.tsx"
    },
    "/login": {
      "filePath": "(auth)/login.lazy.tsx"
    },
    "/post/$postId": {
      "filePath": "post.$postId.lazy.tsx"
    },
    "/_layout/": {
      "filePath": "_layout.index.lazy.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
